name: linux-x64-cpu-gcc
on:
  push:
    branches: [master]
    paths:
    - '.github/workflows/linux-x64-cpu-gcc.yml'
    - 'toolchains/host.gcc-m32.toolchain.cmake'
    - 'CMakeLists.txt'
    - 'build.sh'
    - 'cmake/**'
    - 'src/*'
    - 'src/layer/*'
    - 'src/layer/x86/**'
    - 'examples/**'
    - 'demo/**'
    - 'tests/*'
  pull_request:
    branches: [master]
    paths:
    - '.github/workflows/linux-x64-cpu-gcc.yml'
    - 'toolchains/host.gcc-m32.toolchain.cmake'
    - 'CMakeLists.txt'
    - 'build.sh'
    - 'cmake/**'
    - 'src/*'
    - 'src/layer/*'
    - 'src/layer/x86/**'
    - 'examples/**'
    - 'demo/**'
    - 'tests/*'
concurrency:
  group: linux-x64-cpu-gcc-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  linux-gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: update
      run: sudo apt-get update
    - name: protobuf
      run: sudo apt-get install libprotobuf-dev protobuf-compiler libopencv-dev

    - name: build
      run: |
        bash build.sh init
        mkdir build && cd build
        cmake -DNCNN_BUILD_TESTS=ON -DNCNN_ASAN=ON -DNCNN_BUILD_TOOLS=OFF -DNCNN_SIMPLEOCV=OFF ..
        cmake --build . -j $(nproc)
    - name: run-tests
      run: |
        cd build/tests && ./ncnn_test
    - name: test-demo
      run: |
        cd demo/build && ./squeezenet ../images/cat.jpg
        
    - name: test build.sh
      run: |
        bash build.sh all